services:
  db:
    image: mysql:9.0.1
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: